# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- script: echo 'My First Azure Pipeline with Gradle'
  displayName: 'Run a one-line script'

- script: ./gradlew build
  displayName: 'Build with Gradle'

- script: ./gradlew run
  displayName: 'Run Gradle file'
